name: 'AWS Secrets Manager GitHub Action'
author: 'AWS Secrets Manager'
description: 'GitHub action for retrieving secrets from AWS Secrets Manager'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  secret-ids:
    description: 'One or more secret names, secret ARNs, or secret prefixes to retrieve'
    required: true
  parse-json-secrets:
    description: '(Optional) If true, JSON secrets will be deserialized, creating a secret environment variable for each key-value pair.'
    required: false
    default: 'false'
  overwrite-mode:
    description: '(Optional) Define how to handle overwriting secrets.'
    required: false
    default: 'error'
  public-env-vars:
    description: '(Optional) Treat specific secrets as standard environment variables (unmasked).'
    required: false
    default: ''
  public-numerics:
    description: '(Optional) Treat numeric secrets as standard environment variables (unmasked).'
    required: false
    default: 'false'
  public-values:
    description: '(Optional) Treat specific secret values as standard environment variables values (unmasked).'
    required: false
    default: ''
  output-file:
    description: '(Optional) Path to file that will be populated with all `KEY=VALUE` pairs. This is in addition to injecting in environment.'
    required: false
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
  post: 'dist/cleanup/index.js'
